version: 'LATEST'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      ALLOW_LIST: "true"
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
      - ./allowlist.json:/allowlist.json
    stdin_open: true
    tty: true
